# Generated by Django 3.2.9 on 2021-11-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
    ]
