# Generated by Django 3.2.9 on 2021-11-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211107_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
