# Generated by Django 3.2.9 on 2021-11-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_shopper_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopper',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='username',
        ),
    ]
